version: '3.8'

# Variables para permisos
x-environment:
  &default-user
  UID: ${UID:-1000}
  GID: ${GID:-1000}
services:
  php:
    build: ./php
    container_name: docker_php2
    volumes:
      - ./src:/var/www/html
      - ./php/conf.d/99-xdebug.ini:/usr/local/etc/php/conf.d/99-xdebug.ini

    #usuario para permisos  
    user: "${UID}:${GID}"
    environment:
      <<: *default-user

    networks:
      - app-network
    depends_on:
      - mysql
  #  user: "www-data:www-data"
  

  nginx:
    image: nginx:latest
    container_name: docker_nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: docker_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: alumno
      MYSQL_PASSWORD: alumno
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
